### ISSUE TITLE
すごい広島89 - eiel やること宣言

### ISSUE THREAD

**Issue by eiel** [great-h/great-h.github.io#1508]
* [x] issueの整理
* [x] 87のレポート
* [x] 来週のページをつくる
* [ ] lftpのメモをかく
* [ ] dockrizeしたい
* [ ] ドラッグ&ドロップでファイルをアップロードしたい on rails

**Comment by kakenavi** [comment]
エア参加すらできない。からい。

**Comment by eiel** [comment]
ねむい。
すごい広島87のレポートかいた。

https://www.facebook.com/great.hiroshima/posts/513897075419609
