### ISSUE TITLE
2015/01/28やることリスト

### ISSUE THREAD

**Issue by Akamikun** [great-h/great-h.github.io#1510]
* [x] とある前夜祭の会場の候補を探す

**Comment by Akamikun** [comment]
量の割に安い
* 鉄板 個室 Dining　案山子 本店　飲み放題コース（[ホットペッパー](http://www.hotpepper.jp/strJ000748998/)）で￥3200〜
* 29酒場広島串かっちゃん　飲み食べ放題コース（[ホットペッパー](http://www.hotpepper.jp/strJ000766994/)）で￥4000
　他コースもある

焼肉
* ぶち　流川店　飲み放題コース（[ホットペッパー](http://www.hotpepper.jp/strJ000028215/)）で￥3500〜

お好み焼き
* 若貴　わかたか　[ホットペッパー](http://www.hotpepper.jp/strJ000636003/)

少々お高いがおもてなしのできるお店
* 酒菜処　きっすい　[ホットペッパー](http://www.hotpepper.jp/strJ000521396/)

**Comment by eiel** [comment]
銀華桜 http://www.ginhanasakura.jp/index.html
