### ISSUE TITLE
すごい広島＃97 銀ねこ

### ISSUE THREAD

**Issue by yuririn** [great-h/great-h.github.io#1588]
コンクリのページタイプについてまとめる

**Comment by yuririn** [comment]
ページタイプの機能についてまとめた。
意識した点はできるだけ他の超メジャーなCMSと比較したり（根本的に機能が違うから何とも言えないけど…）できるだけプログラマ目線は外してみた。他にも気になる機能が見つかったここからはメモ「子ページ」「パッケージ」の表示があるのでここら辺をさらに分かりやすく説明できればいーなー。
http://ginneko-atelier.com/blogs/concrete5/317/

**Comment by eiel** [comment]
> 他のCMSと比ながら説明してみると…

「べ」 がぬけてるかもしれない。

CMSとの比較はWordpressとしかしてないから 「Wordpressと比較すると」にすると読者に優しいかも？

> 同じファイルを利用していろんなページタイプを作るには…？

「いろんなページタイプがあって、同じファイルを利用できる」ってことにきづくまでに時間がかかったです。
