### ISSUE TITLE
今日やる事宣言 - omoto(すごいUnity)

### ISSUE THREAD

**Issue by OmotoAkihiro** [great-h/great-h.github.io#1628]
１．OSC用の作品ＵＲＬ記載
http://unityroom.com/games/play/383
よろしくお願いします！

２．VisualStudioとUnityの連携してデバッグしてみる

３．Blenderで服を作る
　makehumanで作ったキャラにBlenderで簡単な服を作ってみる

**Comment by kamera25** [comment]
@OmotoAkihiro 

1番の事、完了しました。修正などあれば、こちらのコメ欄に書いてください。
http://hiroshima-unity.jimdo.com/%E5%8F%82%E5%8A%A0%E8%80%85%E3%81%AE%E6%88%90%E6%9E%9C/
