### ISSUE TITLE
すごい広島108 - Torokunやること

### ISSUE THREAD

**Issue by Torokun** [great-h/great-h.github.io#1638]
* [x] 引越の最終チェックをしよう
* [x] どこかで言わなければ

**Comment by Torokun** [comment]
[外資系OLのぐだぐだ（旧） めんどくさがり向け引越しの荷造り方法](http://toianna.blog.fc2.com/blog-entry-4.html)

**Comment by Uemmra3** [comment]
7-8月に計画中のFxOSハッカソンとかのサポータースタッフにアサインしようかと思ってたけど残念無念

2015-06-10 19:27 GMT+09:00 Kazuya Matsubara <notifications@github.com>:
