### ISSUE TITLE
すごい広島109 - よっちゃんやること

### ISSUE THREAD

**Issue by yoship** [great-h/great-h.github.io#1644]
* [x] ためまっぷプロジェクトスケジュール
* [ ] ためまっぷプロジェクト開発スケジュール共有（Hiroさんに相談しつつ、、）
* [ ] ためまっぷAndroidビルドエラーを佐々木さんに聞く
* [ ] ためまっぷ要件定義・コンセプト
* [ ] ためまっぷプロジェクト説明会準備（定期、FJ、さわやか福祉財団）

**Comment by eiel** [comment]
closeするとあとでみつけられないのでopenさせておくれやす
