### ISSUE TITLE
すごい広島110  やることリスト

### ISSUE THREAD

**Issue by Torokun** [great-h/great-h.github.io#1649]
すごい広島110  やることリスト
* [x] すごい広島 in Tokyoの場所探しの下見
* [x] <del>余裕があれば5374のソースを読むなど</del> → 既に船橋市の5374があったので却下

**Comment by eiel** [comment]
5374といえば、これを移植したかったりする。 http://papamama.codeforsapporo.org/

**Comment by Torokun** [comment]
引越し先の5374でも考えるかなぁと思っていたら、既にあった件
[funabashi-city/5374 at gh-pages](https://github.com/funabashi-city/5374/tree/gh-pages)
[5374(ｺﾞﾐﾅｼ).jp](http://funabashi-city.github.io/5374/)

**Comment by eiel** [comment]
さっすが船橋

**Comment by Torokun** [comment]
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">キッテきた <a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/Ivx98HPn1P">pic.twitter.com/Ivx98HPn1P</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613661846629789696">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> in Tokyo 会場探し。 <a href="http://t.co/Atj6EgbNwI">pic.twitter.com/Atj6EgbNwI</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613662078872649728">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/g3P6LWVtrg">pic.twitter.com/g3P6LWVtrg</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613662630289387520">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/sCc6RPTVWt">pic.twitter.com/sCc6RPTVWt</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613663589006585856">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="und" dir="ltr"><a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/1oLKENtAof">pic.twitter.com/1oLKENtAof</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613668605167689728">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">カフェ･ド･クリエ 丸の内 MY PLAZA店&#10;ここ良さそう&#10; <a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/OW5hVJx4L7">pic.twitter.com/OW5hVJx4L7</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613669633682321408">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet" lang="ja"><p lang="ja" dir="ltr">やっぱりここになっちゃうのかなー？&#10;スターバックスコーヒー 丸ビル <a href="https://twitter.com/hashtag/%E3%81%99%E3%81%94%E3%81%84%E5%BA%83%E5%B3%B6?src=hash">#すごい広島</a> <a href="http://t.co/U9FDfAaS1Z">pic.twitter.com/U9FDfAaS1Z</a></p>&mdash; トロくん（松原和也） (@Toro_kun) <a href="https://twitter.com/Toro_kun/status/613673083937787904">2015, 6月 24</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
