### ISSUE TITLE
生成されたページがおかしい

### ISSUE THREAD

**Issue by Nyoho** [great-h/great-h.github.io#1800]
<img width="250" alt="2016-04-27 22 24 15" src="https://cloud.githubusercontent.com/assets/118150/14853519/cf13f990-0cc6-11e6-9242-9654da16ee85.png">

**Comment by Nyoho** [comment]
botもおかしいですね。きっと同じ原因でしょう。また今度調べる。

> .@NeXTSTEP2OSX #すごい広島 152 は4月6日よ。 場所は ShakeHands だよ。 
http://twitter.com/great_hiroshima/status/727799839761772545

**Comment by eiel** [comment]
CIが失敗してるか、ウェブサイトが繁栄にしっぱいしてるか…かな

**Comment by eiel** [comment]
CI失敗してそう https://github.com/great-h/great-h.github.io/blob/master/event.json

**Comment by Nyoho** [comment]
4/6のままになってますな。

**Comment by eiel** [comment]
なおりました
https://twitter.com/great_hiroshima/status/727816400237150208
