### ISSUE TITLE
すごい広島　Chat

### ISSUE THREAD

**Issue by ThaddeusJiang** [great-h/great-h.github.io#1853]
皆さん

こんにちは、蒋（ショウ）です。
11月から「すごい広島」に参加したけど、皆さんと連絡することがとてもむずかしいと思います。

連絡ために、great-h.slack.com を作りました。
参加したい方は、自分のメールを教えてください。

> メールアドレスを下記に書く、ありがとうございます

**Comment by eiel** [comment]
メモ: websiteのトップとかに招待リンクが貼れないか検討する

**Comment by eiel** [comment]
ちなみにchatworkもあります。
https://www.chatwork.com/g/great-h

**Comment by ThaddeusJiang** [comment]
@eiel そうですか？知らなかったので

でも、slackがとても優秀なので、そのままで削除しない、参加したい方は是非参加してください。

**Comment by eiel** [comment]
@ThaddeusJiang 
チャットサービスが複数あるのは全然構わないので、ばりばりつかいましょう

**Comment by Nyoho** [comment]
@ThaddeusJiang お願いします。https://github.com/great-h/great-h.github.io にある僕のコミットにメールアドレスがあります。

**Comment by ThaddeusJiang** [comment]
@Nyoho メールアドレスは何ですか？　直接的にここに書く、嬉しいです。
