### ISSUE TITLE
事実上のリンク切れ

### ISSUE THREAD

**Issue by nishimotz** [great-h/great-h.github.io#1866]
http://great-h.github.io/

応援してる → ひろしま発 人材集積促進プロジェクト

のリンク先 https://hiro-hata.com/ が別内容のサイトにかわっているので、
サイト消滅であればリンク削除が必要です。

以上、他の人からご指摘いただいて気づきました。

**Comment by eiel** [comment]
bdd883948cd4cc824d5a59c602a04291d41041d9 で対応
